<?php

namespace App\Http\Resources;

class CategoryCollection extends Collection
{

    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}
